services:
  api1: &api1
    container_name: api1
    volumes:
      - ./:/www
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api2:
    <<: *api1
    container_name: api2
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./:/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1
      - api2
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rinha
    networks:
      - app-network
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
networks:
  app-network:
    driver: bridge