services:
  web:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
  php:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./:/www
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rinha
    networks:
      - app-network
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
networks:
  app-network:
    driver: bridge